# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-19 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sygic_id', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('sygic_id', models.CharField(blank=True, max_length=50, null=True)),
                ('city_perex', models.TextField(blank=True, null=True)),
                ('city_desc', models.TextField(blank=True, null=True)),
                ('city_lat', models.FloatField(blank=True, null=True)),
                ('city_lng', models.FloatField(blank=True, null=True)),
                ('city_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True)),
                ('city_low_image', models.CharField(blank=True, max_length=400, null=True)),
                ('city_high_image', models.CharField(blank=True, max_length=400, null=True)),
=======
                ('city_perex', models.TextField(default=None)),
                ('city_desc', models.TextField(default=None)),
                ('city_lat', models.FloatField(default=None)),
                ('city_lng', models.FloatField(default=None)),
                ('city_rate', models.DecimalField(decimal_places=10, default=None, max_digits=11)),
                ('city_low_image', models.CharField(default=None, max_length=400)),
                ('city_high_image', models.CharField(default=None, max_length=400)),
>>>>>>> c4cf9f34011d10f85fd3958287319d614edf217c
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('sygic_id', models.CharField(blank=True, max_length=50, null=True)),
=======
                ('sygic_id', models.CharField(max_length=50)),
>>>>>>> c4cf9f34011d10f85fd3958287319d614edf217c
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sygic_id', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('sygic_id', models.CharField(blank=True, max_length=50, null=True)),
                ('country_perex', models.TextField(blank=True, null=True)),
                ('country_desc', models.TextField(blank=True, null=True)),
                ('country_lat', models.FloatField(blank=True, null=True)),
                ('country_lng', models.FloatField(blank=True, null=True)),
                ('country_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True)),
                ('country_low_image', models.CharField(blank=True, max_length=400, null=True)),
                ('country_high_image', models.CharField(blank=True, max_length=400, null=True)),
=======
                ('country_perex', models.TextField(default=None)),
                ('country_desc', models.TextField(default=None)),
                ('country_lat', models.FloatField(default=None)),
                ('country_lng', models.FloatField(default=None)),
                ('country_rate', models.DecimalField(decimal_places=10, default=None, max_digits=11)),
                ('country_low_image', models.CharField(default=None, max_length=400)),
                ('country_high_image', models.CharField(default=None, max_length=400)),
>>>>>>> c4cf9f34011d10f85fd3958287319d614edf217c
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelPyLands.Continent')),
            ],
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_name', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('sygic_id', models.CharField(blank=True, max_length=50, null=True)),
                ('poi_perex', models.TextField(blank=True, null=True)),
                ('poi_desc', models.TextField(blank=True, null=True)),
                ('poi_lat', models.FloatField(blank=True, null=True)),
                ('poi_lng', models.FloatField(blank=True, null=True)),
                ('poi_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True)),
                ('poi_low_image', models.CharField(blank=True, max_length=400, null=True)),
                ('poi_high_image', models.CharField(blank=True, max_length=400, null=True)),
=======
                ('poi_perex', models.TextField(default=None)),
                ('poi_desc', models.TextField(default=None)),
                ('poi_lat', models.FloatField(default=None)),
                ('poi_lng', models.FloatField(default=None)),
                ('poi_rate', models.DecimalField(decimal_places=10, default=None, max_digits=11)),
                ('poi_low_image', models.CharField(default=None, max_length=400)),
                ('poi_high_image', models.CharField(default=None, max_length=400)),
>>>>>>> c4cf9f34011d10f85fd3958287319d614edf217c
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelPyLands.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelPyLands.Country'),
        ),
    ]
