# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-19 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=50)),
                ('from_date', models.DateTimeField(default=datetime.datetime.now)),
                ('to_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
